version: "3.9"

services:
  app:
    container_name: "docker_app"
    build:
      dockerfile: ./Dockerfile
    command:
      - "python3"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8001"
    ports:
      - "8000:8001"
